### PR TITLE
Add support for windows paths

### LINKED ISSUE #298: ~ is not recognized under Windows
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.0.15063 Build 15063 Microsoft Windows 10 Pro
- **Cerebro.app version**: 0.2.8

## Issue

Cerebro picks up file paths when starting the input with "/" or "\~". Unfortunately only "/" works under windows. The reason might be, that there is no native OS support for "\~". But it could easily be emulated and would be very helpful for Windows users.

### PR DESCRIPTION
**Pull request by Seldaek**
Should fix https://github.com/KELiON/cerebro/issues/298 but I wasn't able to verify it locally, not sure how to best test plugins in the local app.

### CODE REVIEW

**Comment by KELiON** [comment]
@Seldaek you can try to uninstall `cerebro-files-nav` plugin (plugins -> search for files -> uninstall) and after that run `npm run debug` in project directory. It will add development version of plugin to Cerebro, so you can verify that it works

**Comment by Seldaek** [comment]
I run npm run debug and got this from webpack:

```
ERROR in ./~/cerebro-ui/Loading/index.js
Module parse failed: ...\cerebro-files-nav\node_modules\cerebro-ui\Loading\index.js Unexpected token (5:2)
You may need an appropriate loader to handle this file type.
|
| export default () => (
|   <div className={styles.spinner}>
|     <div className={styles.bounce1}></div>
|     <div className={styles.bounce2}></div>
 @ ./~/cerebro-ui/index.js 1:0-47
 @ ./src/Preview/previews/Pdf.js
 @ ./src/Preview/index.js
 @ ./src/index.js
```

The symlink is there, but even after restarting cerebro the files-nav plugin is not enabled so I can't check if it works :/

**Comment by KELiON** [comment]
@Seldaek I've just updated development scripts. Can you update your branch and try again? To do it you can try to run:

```
git fetch --all 
git rebase origin/master
rm -rf ./node_modules
yarn
yarn start
```

But make sure that you have `yarn` [installed](https://yarnpkg.com/lang/en/docs/install/) globally

**Comment by Seldaek** [comment]
Note that I still get the same error when running the yarn install:

```
ERROR in ./~/cerebro-ui/Loading/index.js
Module parse failed: ~\cerebro-files-nav\node_modules\cerebro-ui\Loading\index.js Unexpected token (5:2)
You may need an appropriate loader to handle this file type.
|
| export default () => (
|   <div className={styles.spinner}>
|     <div className={styles.bounce1}></div>
|     <div className={styles.bounce2}></div>
 @ ./~/cerebro-ui/index.js 1:0-47
 @ ./src/Preview/previews/Pdf.js
 @ ./src/Preview/index.js
 @ ./src/index.js

ERROR in ./~/cerebro-ui/KeyboardNav/index.js
Module parse failed: ~\cerebro-files-nav\node_modules\cerebro-ui\KeyboardNav\index.js Unexpected token (79:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <div onKeyDown={this.onKeyDown.bind(this)} ref={(el) => { this.wrapper = el }}>
|         {this.props.children}
|       </div>
 @ ./~/cerebro-ui/index.js 2:0-55
 @ ./src/Preview/previews/Pdf.js
 @ ./src/Preview/index.js
 @ ./src/index.js

ERROR in ./~/cerebro-ui/KeyboardNavItem/index.js
Module parse failed: ~\cerebro-files-nav\node_modules\cerebro-ui\KeyboardNavItem\index.js Unexpected token (4:36)
You may need an appropriate loader to handle this file type.
| import styles from './styles.css'
|
```

And then with yarn start

```
$ yarn start
yarn start v0.27.5
$ cerebro-scripts start
~\cerebro-files-nav\node_modules\cerebro-scripts\scripts\start.js:37
    appname,
    ^

ReferenceError: appname is not defined
    at Object.<anonymous> (~\cerebro-files-nav\node_modules\cerebro-scripts\scripts\start.js:37:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by Seldaek** [comment]
I'll try and fix the start script for windows and send a PR.

**Comment by Seldaek** [comment]
https://github.com/KELiON/create-cerebro-plugin/pull/1 fixes the start errors, but those 3 errors from webpack seem to be causing issues. Cerebro does not start (I'm not sure if it is supposed to) and if I start it by hand even though the symlink exists the plugin is not loaded.

**Comment by Seldaek** [comment]
Hmm, it seems to fail on JS syntax, so maybe I need to upgrade nodejs to a new version.. I'll try that.

**Comment by Seldaek** [comment]
No change with nodejs 6.11.1 (latest LTS). Not sure what's up with the webpack config but something seems off.

**Comment by KELiON** [comment]
@Seldaek I think there is one more bug in `cerebro-scripts`. This [rule](https://github.com/KELiON/create-cerebro-plugin/blob/master/packages/cerebro-scripts/config/webpack.config.js#L39) used to show, that all packages in node_modules, that starts with `cerebro-` should be transpiled with babel, but regexp here is `/node_modules\/cerebro-/`, so, it uses `/` slash as a path folder. So, I think changing it to both slashes (for windows and for unix) should solve your issue

**Comment by Seldaek** [comment]
Yeah i was about to send a PR for that :) That indeed makes the webpack build pass.

**Comment by Seldaek** [comment]
The files nav plugin still isn't loaded though.. How do I actually load it/run it in cerebro?

**Comment by KELiON** [comment]
@Seldaek can you check Cerebro developer tools? For me on mac it is loaded as soon as webpack build works. If it doesn't in your case – try to reload (developer -> reload) Cerebro, but information from console can show more details about plugin loading

**Comment by Seldaek** [comment]
Ehh I have developer mode enabled, but I don't see any dev tools. It's now running via `yarn run dev` but still no plugin loaded, and the font rendering is a bit weird:

image


I got this warning when running `yarn run dev`:

```
[0] WARNING in ./node_modules/execa/node_modules/cross-spawn/index.js
[0] Module not found: Error: Can't resolve 'spawn-sync' in '~\cerebro\node_modules\execa\node_modules\cross-spawn'
[0]  @ ./node_modules/execa/node_modules/cross-spawn/index.js 32:26-47
```

But otherwise it all built fine..

Really not sure what's up at this point :/

**Comment by KELiON** [comment]
@Seldaek to enable developer tools: type settings -> Cerebro settings -> show in menu bar -> menu bar icon -> developer -> dev. tools (main)

So, after reloading Cerebro you still don't see your plugin, right?

**Comment by Seldaek** [comment]
Yup, the Files Nav plugin is still missing.. The symlink is there though.. just doesn't load it. 

Thanks for the dev tools, I got that to load at least now :)

**Comment by Seldaek** [comment]
What's really weird is the console in dev tools shows:

Load plugin: cerebro-files-nav
externalPlugins.js:61 Path: C:\Users\seld\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-files-nav...

Also there's an error about file:///.../cerebro/app/dist/main/css/themes/light.css not being found, which probably explains why the rendering is messed up. Do I have to run anything else than yarn install in the app dir?

**Comment by KELiON** [comment]
@Seldaek can you please attach full output from console?

**Comment by Seldaek** [comment]
Here you go:

image
image

**Comment by KELiON** [comment]
@Seldaek looks like plugin is loaded and should work, nothing critical related to the plugin is here. You can try to debug it using `console.log` or debugger statements in plugin function

**Comment by Seldaek** [comment]
@KELiON ok indeed it was loaded. I still have the bug with the font doing some double rendering, and well the font rendering incorrectly altoghter:

image

But anyway I pushed a fix for the branch, so it is now confirmed to work with `~/foo` on windows, and I also added a [second commit](https://github.com/KELiON/cerebro-files-nav/pull/2/commits/918c6fcb80852334b283a05ed9b7d4ec185d2547) which autocompletes directories with a trailing / or \ on windows. This allows you to traverse deep directory structures by just hitting tab repeatedly, no need to do tab then / then tab then / then tab etc.. :)

**Comment by ikupenov** [comment]
Any update on this?

**Review by ikupenov — APPROVED** [review]

**Review by KELiON — APPROVED** [review]
LGTM for me! 👍

**Comment by mokhosh** [comment]
is this supposed to be working now? i have version 1.0.4

UPDATE: i can see my User forlder using ~/ but i can't navigate other drives like d: or g:

**Comment by KELiON** [comment]
@safir187 yep, this PR is included in v1.0.4. Does it work for you @Seldaek?

**Comment by ikupenov** [comment]
It does work but you can't change drives as mentioned.

**Pull request merged**
